// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8ANL6DE8S2x2HU-S4TjWf5jfUS3TS51Q',
    appId: '1:322886757690:web:3340467386802465993403',
    messagingSenderId: '322886757690',
    projectId: 'my-chat-app-v1-cafb5',
    authDomain: 'my-chat-app-v1-cafb5.firebaseapp.com',
    storageBucket: 'my-chat-app-v1-cafb5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGDET5KHR5JNO0yuee3rSYyWYea66wL7E',
    appId: '1:322886757690:android:94a64c66d408199d993403',
    messagingSenderId: '322886757690',
    projectId: 'my-chat-app-v1-cafb5',
    storageBucket: 'my-chat-app-v1-cafb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyRNiq0lXoNa6nO05NAvZ2cjPT85sctz0',
    appId: '1:322886757690:ios:4c30031b107ae873993403',
    messagingSenderId: '322886757690',
    projectId: 'my-chat-app-v1-cafb5',
    storageBucket: 'my-chat-app-v1-cafb5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
